### ISSUE TITLE
License

### ISSUE THREAD

**Issue by caesar** [jakob-e/unitconversion#3]
Hey, this is a great set of conversion functions.

Do you think you could add a license statement to the readme (or a LICENSE.txt file) so that I and others know if we can use it in projects?

If you're undecided on which license, MIT would be ideal... :-)

Thanks!

**Comment by jakob-e** [comment]
@caesar Thank you for the kind words – I never intended it to be anything but free why the MIT licence is hereby added :-)

**Comment by caesar** [comment]
@jakob-e you're awesome! Thanks for all your hard work.
