### ISSUE TITLE
[propopsal] `$root-unit`

### ISSUE THREAD

**Issue by kgcreative** [jakob-e/unitconversion#4]
It may be that mine is a pretty big edge case, but I figured I'd throw this out for discussion.

Is there a use for a `$root-unit` variable to be added in addition to `$base-unit`?

As i'm instantiating a new project, i've set a HTML root font size of 62.5%, which effectively resets my REM units to be decimal in relation to PX. (i.e. 10px = 1rem) -- This simplifies REM lengths with PX fallbacks, but it has the unintended consequence of making the rem(unit) function pretty much useless in this context, since I set my body font-size to 1.6em, and calculate units sizes relatively from body, instead of the root HTML size.

By allowing a different REM variable for calculating REM to EM, this would solve my issue, but I'm not sure if this particular project was setup with that in mind, or if it's even appropriate to make an allowance for this here.

In this instance, only using `$root-unit` for REMs, and using `$base-unit` for everything else works perfectly, which could be instantiated conditionally via

```
$base-unit: 16px! default
$root-unit: $base-unit !default
```

I can try and figure out a pull request to add this behavior, if you feel it's appropriate to this project, but before I do so I wanted to open this to discussion, since there may be several unintended consequences I haven't considered when it comes to unit conversion.

**Comment by jakob-e** [comment]
@kgcreative Thank you for the feedback – much appreciated

I see your point and I'm open for anything that does not conflict with visual pixel size (px to me is like the native language of css units).
````
          visual size
rem(32px) => 32px  
em(32px)  => 32px
`````
I'll try to implement two relative length sizes and run some tests.... I've been thinking of re-viewing the code for some time anyways.

If you find the time please make a pull request – two minds works better than one :-)

**Comment by kgcreative** [comment]
PR sent.

I tested via:
```
scss:
$root-font-size: 10px;
$base-font-size: 18px;

.test-element-em {
  font-size: em(18px);
}
.test-element-rem {
  font-size: rem(18px);
}
.test-element-em-to-rem {
  font-size: rem(1em);
}
.test-element-rem-to-em {
  font-size: em(1rem);
}
.test-element-rem-to-px {
  font-size: px(1rem);
}
.test-element-em-to-px {
  font-size: px(1em);
}

output:
.test-element-em {
  font-size: 1em;
}
.test-element-rem {
  font-size:1.8rem;
}
.test-element-em-to-rem {
  font-size: 1.8rem;
}
.test-element-rem-to-em {
  font-size: .555555555556em;
}

.test-element-rem-to-px {
  font-size: 10px;
}
.test-element-em-to-px {
  font-size: 18px;
}

```

**Comment by jakob-e** [comment]
Closing via #5
