### ISSUE TITLE
Unitless value question

### ISSUE THREAD

**Issue by CGTS** [jakob-e/unitconversion#7]
This isn't an issue with this project or even something that needs to be included in the functionality, just a question for my specific needs.

How could I make it so unitless numbers are seen as a multiplier of my baseline (line-height). For example if I set-up my document with a `base-font-size: 16px` and a `base-line-height: 1.5 (or 24px)` and I used the conversion of px(1) it would then return 24px? or have a unitless(24px) return 1.5 etc...

Any help is appreciated.

**Comment by jakob-e** [comment]
Sorry for being late in my reply. Im not sure why you would convert baselines as 1.5 works on all font sizes. Having said that you could create a baseline conversion function – like:

Please note that one of the features about conversion is the ability to "roll back" – saying if you do multiple conversions your input should match the output e.g.   px( em( cm( 16px ) ) ) => 16px

````SCSS
$base-font-size: 16px;
$base-line-height: 1.5;
@function bl($input){
    @return if(
        unitless($input),
        $input / $base-line-height * $base-font-size,
        px($input) / $base-font-size * $base-line-height 
    );
}


test {
    value: bl(1);        // 10.66667px (16px/1.5)
    value: bl(bl(1));    // 1    (converting to px then back => output = input)   
    value: bl(16px);     // 1.5  
    value: bl(16em);     // 1.5
    value: bl(24px);     // 2.25
    value: bl(bl(24px)); // 24px (converting to base lines then back => output = input)   
}

**Comment by CGTS** [comment]
I really appreciate it the help on this. I know it's a strange case, I've been using https://github.com/jptaranto/typey lately and I wanted to add some functionality that mimicked the `spacing` function used in it, while being looser with the units allowed. 

I'll give this a shot thanks again.
